server:
  port: 50004
  ssl:
    enabled: true
    key-store: classpath:eureka.jks
    key-store-password: ************
    key-alias: eureka

eureka:
  client:
    securePortEnabled: true
    region: default
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://localhost:58761/eureka}
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    preferIpAddress: true

spring:
  datasource:
    url: jdbc:oracle:thin:*************
    username: *********
    password: ***********
  batch:
    job:
      enabled: false