server:
  port: 50001

eureka:
  client:
    region: default
    fetchRegistry: true
    registryFetchIntervalSeconds: 1
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:58761/eureka}
  instance:
    preferIpAddress: true

spring:
  datasource:
    url: jdbc:oracle:thin:@//172.17.110.122:1521/essp
    username: system
    password: manager
  batch:
    job:
      enabled: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


batch:
  maxBatchNumber: 4
  entryDir: C:/bsb/usci/batch-entries
  save:
    dir: C:/bsb/usci/batches/upload
  uploads:
    dir: C:/bsb/usci/batches/download


sync:
  host: 127.0.0.1

cluster: 1

kafka:
  bootstrap-server: 10.10.32.148:9092
  consumer-group: usci
  topic: RECEIVER