server:
  port: 58761
  ssl:
    enabled: true
    key-store: classpath:eureka.jks
    key-store-password: ************
    key-alias: eureka

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: https://10.8.1.58:58761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
    eviction-interval-timer-in-ms: 2000
  instance:
    hostname: 10.8.1.58
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}