server:
  port: 50002
  ssl:
    enabled: true
    key-store: classpath:eureka.jks
    key-store-password: **************
    key-alias: eureka

eureka:
  client:
    securePortEnabled: true
    region: default
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://localhost:58761/eureka}
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

spring:
  datasource:
    url: jdbc:oracle:thin:**********
    username: *********
    password: ************

sync:
  threadLimit: 100

kafka:
  bootstrap-server: 10.8.1.191:9092