server:
  port: 50002

eureka:
  client:
    region: default
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:58761/eureka}
  instance:
    preferIpAddress: true

spring:
  datasource:
    url: jdbc:oracle:thin:**********
    username: *****
    password: ***********

sync:
  threadLimit: 1000

kafka:
  bootstrap-server: 10.10.32.148:9092
