server:
  port: 50006

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:58761/eureka}
  instance:
    preferIpAddress: true

spring:
  datasource:
    url: jdbc:oracle:thin:*********
    username: **********
    password: ************

jasper:
  templatePath: D:/essp/Portal_afn/template/Report/
  reportFilesFolder: D:/essp/Portal_afn/generated_reports/
  recordBySheet: 50000

