server:
  port: 50007
  ssl:
    enabled: true
    key-store: classpath:eurekaclient.jks
    key-store-password: eurekaclient
    key-alias: eurekaclient
    trust-store: classpath:eurekaclient.jks
    trust-store-password: eurekaclient

eureka:
  client:
    securePortEnabled: true
    region: default
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://localhost:58761/eureka}
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    preferIpAddress: true

spring:
  datasource:
    url: jdbc:oracle:thin:@//10.8.1.163:1521/essp
    username: eav_backend
    password: 1

wsclient:
  kgdUrl: 10.8.255.50:1274
  gbdul:
    url: http://10.8.255.50:3771/
    username: VCON_GBD
    password: Qwerty_123