server:
  port: 50007

eureka:
  client:
    region: default
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:58761/eureka}
  instance:
    preferIpAddress: true

spring:
  datasource:
    url: jdbc:oracle:thin:************
    username: system
    password: manager

wsclient:
  kgdUrl: 10.10.32.198:1272
  gbdul:
    url: http://10.8.255.50:3771/
    username: ************
    password: ***************