server:
  port: 50099
  ssl:
    enabled: true
    key-store: classpath:eurekaclient.jks
    key-store-password: eurekaclient
    key-alias: eurekaclient
    trust-store: classpath:eurekaclient.jks
    trust-store-password: eurekaclient

eureka:
  client:
    securePortEnabled: true
    region: default
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://localhost:58761/eureka}
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}

spring:
  datasource:
    url: jdbc:oracle:thin:@//10.8.1.143:1521/essp
    username: eav_backend
    password: 1

batch:
  wsDir: /mnt/sdb1/bsb/usci/ws-batches

wso2:
  provider:
    clientId: f53W2xAyOkIORwswHuskabACYLQa
    clientSecret: aClm5ccJuoinzGnEyk68qm7J8sYa
  token:
    url: https://idp.nationalbank.kz/oauth2/token
    introspectUrl: https://idp.nationalbank.kz/oauth2/introspect
pki:
  ocsp:
    url: http://ocsp.pki.gov.kz
    cer: pki_gost.cer
logging:
  level:
    root: all

